In [1]:
from google.colab import drive
drive.mount('/content/drive')

caminho_dados = "/content/drive/MyDrive/ESTUDOS ANALISE CIENCIA DE DADOS/dados_saude.xlsx"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd


df_planosaude = pd.read_excel(caminho_dados)

df_planosaude = df_planosaude.loc[:, ~df_planosaude.columns.str.contains('^Unnamed')]

display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1

In [3]:
top10_maioresgastos_sinistralidade = df_planosaude.nlargest(15, 'Sinistro_Anual')
display(top10_maioresgastos_sinistralidade)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0

In [4]:
df_planosaude['Sinistralidade'] = (df_planosaude['Sinistro_Anual'] / (df_planosaude['Mensalidade'] * 12)) * 100
df_planosaude['Sinistralidade'] = df_planosaude['Sinistralidade'].round(0).astype(str) + '%'
display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes,Sinistralidade
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0,22.0%
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1,98.0%
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0,10.0%
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2,118.0%
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0,0.0%
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3,101.0%
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0,18.0%
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0,56.0%
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0,9.0%
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1,153.0%
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0,14.0%
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0,39.0%
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4,139.0%
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0,3.0%
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1,79.0%

In [5]:
df_planosaude.sort_values(by='Sinistralidade', ascending=False)
display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes,Sinistralidade
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0,22.0%
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1,98.0%
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0,10.0%
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2,118.0%
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0,0.0%
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3,101.0%
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0,18.0%
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0,56.0%
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0,9.0%
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1,153.0%
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0,14.0%
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0,39.0%
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4,139.0%
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0,3.0%
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1,79.0%

In [6]:
if df_planosaude['Sinistralidade'].dtype == 'object':
    df_planosaude['Sinistralidade'] = df_planosaude['Sinistralidade'].str.replace('%', '').astype(float)

bins = [0, 20, 50, 100, 300]
labels = ['Muito Baixo', 'Médio', 'Alto', 'Crítico']

df_planosaude['Classificacao_Sinistralidade'] = pd.cut(df_planosaude['Sinistralidade'], bins=bins, labels=labels)

print(df_planosaude[['Nome', 'Sinistralidade', 'Classificacao_Sinistralidade']])

             Nome  Sinistralidade Classificacao_Sinistralidade
0       Ana Silva            22.0                        Médio
1     Bruno Costa            98.0                         Alto
2      Carla Dias            10.0                  Muito Baixo
3     Diego Souza           118.0                      Crítico
4   Elena Martins             0.0                          NaN
5      Fabio Lima           101.0                      Crítico
6    Gisele Rocha            18.0                  Muito Baixo
7    Humberto Vaz            56.0                         Alto
8      Iris Gomes             9.0                  Muito Baixo
9      João Paulo           153.0                      Crítico
10      Karen Luz            14.0                  Muito Baixo
11     Lucas Melo            39.0                        Médio
12    Mariana Paz           139.0                      Crítico
13      Nuno Reis             3.0                  Muito Baixo
14     Olivia Sol            79.0                         Alto

In [7]:
alvos = ['Alto', 'Crítico']

df_filtro_risco = df_planosaude[df_planosaude['Classificacao_Sinistralidade'].isin(alvos)]
print(df_filtro_risco)

    ID          Nome  Idade Sexo        Regiao  Plano  Sinistro_Anual  \
1    2   Bruno Costa     45    M           Sul  Prata         8500.00
3    4   Diego Souza     58    M  Centro-Oeste   Ouro        15600.75
5    6    Fabio Lima     67    M           Sul   Ouro        22400.00
7    8  Humberto Vaz     29    M       Sudeste  Prata         3200.00
9   10    João Paulo     38    M           Sul  Prata        12500.40
12  13   Mariana Paz     71    F           Sul   Ouro        35000.00
14  15    Olivia Sol     48    F       Sudeste  Prata         7400.00

    Mensalidade Fumante  Internacoes  Sinistralidade  \
1           720     Sim            1            98.0
3          1100     Sim            2           118.0
5          1850     Nao            3           101.0
7           480     Nao            0            56.0
9           680     Sim            1           153.0
12         2100     Nao            4           139.0
14          780     Sim            1            79.0

   Classificacao_Sinistralidade
1                          Alto
3                       Crítico
5                       Crítico
7                          Alto
9                       Crítico
12                      Crítico
14                         Alto

In [8]:
df_planosaude['Sinistro_Anual'] = pd.to_numeric(df_planosaude['Sinistro_Anual'])

Total_Gastos_da_Empresa = df_planosaude['Sinistro_Anual'].sum().astype(int)

Total_Gastos_filtrorisco = df_filtro_risco['Sinistro_Anual'].sum().astype(int)

print(f"Total de Gastos da Empresa: ", Total_Gastos_da_Empresa)

print(f"Total de Gastos de Pacientes com alta sinistralidade:", Total_Gastos_filtrorisco)

Total de Gastos da Empresa:  113331
Total de Gastos de Pacientes com alta sinistralidade: 104601

In [9]:
contagem = df_planosaude['Fumante'].value_counts()
print(contagem)

Fumante
Nao    11
Sim     4
Name: count, dtype: int64

In [10]:
analise_fumo = df_filtro_risco.groupby(['Fumante'])['Sinistro_Anual'].sum()

print(analise_fumo)

Fumante
Nao    60600.00
Sim    44001.15
Name: Sinistro_Anual, dtype: float64

In [11]:
print(f"Encontrados {len(df_filtro_risco)} casos para atenção imediata:")
print(df_filtro_risco[['Nome', 'Sinistralidade', 'Classificacao_Sinistralidade']])

Encontrados 7 casos para atenção imediata:
            Nome  Sinistralidade Classificacao_Sinistralidade
1    Bruno Costa            98.0                         Alto
3    Diego Souza           118.0                      Crítico
5     Fabio Lima           101.0                      Crítico
7   Humberto Vaz            56.0                         Alto
9     João Paulo           153.0                      Crítico
12   Mariana Paz           139.0                      Crítico
14    Olivia Sol            79.0                         Alto

In [12]:
media_sinistro_risco = df_filtro_risco['Sinistro_Anual'].mean().astype(int)
media_sinistro_geral = df_planosaude['Sinistro_Anual'].mean().astype(int)

print(f"Média de Sinistro para Pacientes com Alta Sinistralidade: {media_sinistro_risco}")
print(f"Média de Sinistro Geral: {media_sinistro_geral}")

Média de Sinistro para Pacientes com Alta Sinistralidade: 14943
Média de Sinistro Geral: 7555

In [13]:
!pip install streamlit plotly

Collecting streamlit
  Downloading streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.55.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 51.6 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 80.2 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.55.0

In [15]:
import streamlit as st
import pandas as pd
import plotly.express as px # Biblioteca excelente para gráficos interativos

st.set_page_config(page_title="Dashboard de Sinistralidade", layout="wide")

st.title("Análise de Sinistralidade - Operadora de Saúde")

st.sidebar.header("Filtros")
categoria = st.sidebar.multiselect(
    "Selecione a Categoria de Risco:",
    options=df_planosaude['Classificacao_Sinistralidade'].unique(),
    default=['Alto', 'Crítico']
)

df_filtrado = df_planosaude[df_planosaude['Classificacao_Sinistralidade'].isin(categoria)]

col1, col2, col3 = st.columns(3)
col1.metric("Gasto Total (Filtrado)", f"R$ {df_filtrado['Sinistro_Anual'].sum():,.2f}")
col2.metric("Nº de Beneficiários", len(df_filtrado))
col3.metric("Sinistralidade Média", f"{df_filtrado['Sinistralidade'].mean():.1f}%")

st.markdown("---")
c1, c2 = st.columns(2)

with c1:
    st.subheader("Distribuição por Categoria")
    fig_barra = px.bar(df_planosaude['Classificacao_Sinistralidade'].value_counts(), color_discrete_sequence=['#636EFA'])
    st.plotly_chart(fig_barra, use_container_width=True)

with c2:
    st.subheader("Custo: Fumantes vs Não Fumantes")
    fig_box = px.box(df_planosaude, x="Fumante", y="Sinistro_Anual", color="Fumante")
    st.plotly_chart(fig_box, use_container_width=True)

st.subheader("Lista de Beneficiários Filtrados")
st.dataframe(df_filtrado[['Nome', 'Idade', 'Sinistralidade', 'Classificacao_Sinistralidade']])

2026-03-09 23:42:58.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.855 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.859 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.861 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.935 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-03-09 23:42:58.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.938 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.976 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-03-09 23:42:58.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:58.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:42:59.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()