<a href="https://colab.research.google.com/github/KevinMascarenhas/Analise_de_dados_treinos_e_estudos/blob/main/Analise_Plano_de_Saude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

caminho_dados = "/content/drive/MyDrive/ESTUDOS ANALISE CIENCIA DE DADOS/dados_saude.xlsx"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. Introdução / Análise do Problema

Uma clínica médica tem lidado com uma alta quantidade de sinistros no último ano. A clínica busca identificar quanto gasto com esses sinistros, identificar e filtrar quais pacientes mais contribuem com esses gastos e filtrar e classificar pacientes que podem ter possíveis sinistros futuramente.

In [8]:
import pandas as pd


df_planosaude = pd.read_excel(caminho_dados)

df_planosaude = df_planosaude.loc[:, ~df_planosaude.columns.str.contains('^Unnamed')]

display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1

In [9]:
top10_maioresgastos_sinistralidade = df_planosaude.nlargest(15, 'Sinistro_Anual')
display(top10_maioresgastos_sinistralidade)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0

In [10]:
df_planosaude['Sinistralidade'] = (df_planosaude['Sinistro_Anual'] / (df_planosaude['Mensalidade'] * 12)) * 100
df_planosaude['Sinistralidade'] = df_planosaude['Sinistralidade'].round(0).astype(str) + '%'
display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes,Sinistralidade
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0,22.0%
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1,98.0%
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0,10.0%
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2,118.0%
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0,0.0%
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3,101.0%
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0,18.0%
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0,56.0%
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0,9.0%
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1,153.0%
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0,14.0%
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0,39.0%
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4,139.0%
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0,3.0%
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1,79.0%

In [11]:
df_planosaude.sort_values(by='Sinistralidade', ascending=False)
display(df_planosaude)

,ID,Nome,Idade,Sexo,Regiao,Plano,Sinistro_Anual,Mensalidade,Fumante,Internacoes,Sinistralidade
0,1,Ana Silva,24,F,Sudeste,Ouro,1200.50,450,Nao,0,22.0%
1,2,Bruno Costa,45,M,Sul,Prata,8500.00,720,Sim,1,98.0%
2,3,Carla Dias,32,F,Nordeste,Bronze,450.00,380,Nao,0,10.0%
3,4,Diego Souza,58,M,Centro-Oeste,Ouro,15600.75,1100,Sim,2,118.0%
4,5,Elena Martins,19,F,Sudeste,Prata,0.00,410,Nao,0,0.0%
5,6,Fabio Lima,67,M,Sul,Ouro,22400.00,1850,Nao,3,101.0%
6,7,Gisele Rocha,41,F,Norte,Bronze,1150.20,520,Nao,0,18.0%
7,8,Humberto Vaz,29,M,Sudeste,Prata,3200.00,480,Nao,0,56.0%
8,9,Iris Gomes,52,F,Nordeste,Ouro,980.00,950,Nao,0,9.0%
9,10,João Paulo,38,M,Sul,Prata,12500.40,680,Sim,1,153.0%
10,11,Karen Luz,26,F,Sudeste,Bronze,600.00,350,Nao,0,14.0%
11,12,Lucas Melo,44,M,Norte,Ouro,4200.00,890,Nao,0,39.0%
12,13,Mariana Paz,71,F,Sul,Ouro,35000.00,2100,Nao,4,139.0%
13,14,Nuno Reis,35,M,Centro-Oeste,Bronze,150.00,420,Nao,0,3.0%
14,15,Olivia Sol,48,F,Sudeste,Prata,7400.00,780,Sim,1,79.0%

In [12]:
if df_planosaude['Sinistralidade'].dtype == 'object':
    df_planosaude['Sinistralidade'] = df_planosaude['Sinistralidade'].str.replace('%', '').astype(float)

bins = [0, 20, 50, 100, 300]
labels = ['Muito Baixo', 'Médio', 'Alto', 'Crítico']

df_planosaude['Classificacao_Sinistralidade'] = pd.cut(df_planosaude['Sinistralidade'], bins=bins, labels=labels)

print(df_planosaude[['Nome', 'Sinistralidade', 'Classificacao_Sinistralidade']])

             Nome  Sinistralidade Classificacao_Sinistralidade
0       Ana Silva            22.0                        Médio
1     Bruno Costa            98.0                         Alto
2      Carla Dias            10.0                  Muito Baixo
3     Diego Souza           118.0                      Crítico
4   Elena Martins             0.0                          NaN
5      Fabio Lima           101.0                      Crítico
6    Gisele Rocha            18.0                  Muito Baixo
7    Humberto Vaz            56.0                         Alto
8      Iris Gomes             9.0                  Muito Baixo
9      João Paulo           153.0                      Crítico
10      Karen Luz            14.0                  Muito Baixo
11     Lucas Melo            39.0                        Médio
12    Mariana Paz           139.0                      Crítico
13      Nuno Reis             3.0                  Muito Baixo
14     Olivia Sol            79.0                         Alto

# 2. Análise Geral

Aqui, tentaremos analisar mais a fundo, analisando cenários de pacientes de risco, pacientes com alta sinistralidade, maior quantidade de internações, entre outros fatores.

In [13]:
alvos = ['Alto', 'Crítico']

df_filtro_risco = df_planosaude[df_planosaude['Classificacao_Sinistralidade'].isin(alvos)]
print(df_filtro_risco)

    ID          Nome  Idade Sexo        Regiao  Plano  Sinistro_Anual  \
1    2   Bruno Costa     45    M           Sul  Prata         8500.00
3    4   Diego Souza     58    M  Centro-Oeste   Ouro        15600.75
5    6    Fabio Lima     67    M           Sul   Ouro        22400.00
7    8  Humberto Vaz     29    M       Sudeste  Prata         3200.00
9   10    João Paulo     38    M           Sul  Prata        12500.40
12  13   Mariana Paz     71    F           Sul   Ouro        35000.00
14  15    Olivia Sol     48    F       Sudeste  Prata         7400.00

    Mensalidade Fumante  Internacoes  Sinistralidade  \
1           720     Sim            1            98.0
3          1100     Sim            2           118.0
5          1850     Nao            3           101.0
7           480     Nao            0            56.0
9           680     Sim            1           153.0
12         2100     Nao            4           139.0
14          780     Sim            1            79.0

   Classificacao_Sinistralidade
1                          Alto
3                       Crítico
5                       Crítico
7                          Alto
9                       Crítico
12                      Crítico
14                         Alto

In [14]:
df_planosaude['Sinistro_Anual'] = pd.to_numeric(df_planosaude['Sinistro_Anual'])

Total_Gastos_da_Empresa = df_planosaude['Sinistro_Anual'].sum().astype(int)

Total_Gastos_filtrorisco = df_filtro_risco['Sinistro_Anual'].sum().astype(int)

print(f"Total de Gastos da Empresa: ", Total_Gastos_da_Empresa)

print(f"Total de Gastos de Pacientes com alta sinistralidade:", Total_Gastos_filtrorisco)

# Pacientes em estado "Alto" ou "Crítico" de Sinistralidade são responsáveis por R$ 104.660 gastos com sinistros. Somando com pacientes em estado "Médio" ou "Muito baixo", são R$ 113.330.

Total de Gastos da Empresa:  113331
Total de Gastos de Pacientes com alta sinistralidade: 104601

In [15]:
contagem = df_planosaude['Fumante'].value_counts()
print(contagem)

Fumante
Nao    11
Sim     4
Name: count, dtype: int64

In [16]:
analise_fumo = df_filtro_risco.groupby(['Fumante'])['Sinistro_Anual'].sum()

print(analise_fumo)

# Mesmo havendo somente 4 fumantes entre 15 pacientes, os custos de sinistro com esse grupo chegam a quase 50%.

Fumante
Nao    60600.00
Sim    44001.15
Name: Sinistro_Anual, dtype: float64

In [17]:
print(f"Encontrados {len(df_filtro_risco)} casos para atenção imediata:")
print(df_filtro_risco[['Nome', 'Idade', 'Sinistralidade', 'Classificacao_Sinistralidade']])

Encontrados 7 casos para atenção imediata:
            Nome  Idade  Sinistralidade Classificacao_Sinistralidade
1    Bruno Costa     45            98.0                         Alto
3    Diego Souza     58           118.0                      Crítico
5     Fabio Lima     67           101.0                      Crítico
7   Humberto Vaz     29            56.0                         Alto
9     João Paulo     38           153.0                      Crítico
12   Mariana Paz     71           139.0                      Crítico
14    Olivia Sol     48            79.0                         Alto

In [18]:
media_sinistro_risco = df_filtro_risco['Sinistro_Anual'].mean().astype(int)
media_sinistro_geral = df_planosaude['Sinistro_Anual'].mean().astype(int)

print(f"Média de Sinistro para Pacientes com Alta Sinistralidade: {media_sinistro_risco}")
print(f"Média de Sinistro Geral: {media_sinistro_geral}")

Média de Sinistro para Pacientes com Alta Sinistralidade: 14943
Média de Sinistro Geral: 7555

In [19]:
bins_idade = [0, 29, 49, 100]
labels_idade = ['Jovem', 'Adulto', 'Sênior']
df_planosaude['Faixa_Etaria'] = pd.cut(df_planosaude['Idade'], bins=bins_idade, labels=labels_idade)
df_planosaude.groupby('Faixa_Etaria')[['Sinistro_Anual', 'Internacoes']].mean().astype(int)

/tmp/ipykernel_237/2230789499.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_planosaude.groupby('Faixa_Etaria')[['Sinistro_Anual', 'Internacoes']].mean().astype(int)

              Sinistro_Anual  Internacoes
Faixa_Etaria
Jovem                   1250            0
Adulto                  4907            0
Sênior                 18495            2

In [20]:
df_planosaude.groupby('Plano')[['Sinistro_Anual', 'Sinistralidade', 'Internacoes']].mean()

        Sinistro_Anual  Sinistralidade  Internacoes
Plano
Bronze      587.550000       11.250000          0.0
Ouro      13230.208333       71.333333          1.5
Prata      6320.080000       77.200000          0.6